
| distributed init (rank 2): env://, gpu 2
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fd871a35550>
Traceback (most recent call last):
  File "/home/sooh/.conda/envs/myenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/sooh/.conda/envs/myenv/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1423, in _shutdown_workers
    self._worker_result_queue.put((None, None))
  File "/home/sooh/.conda/envs/myenv/lib/python3.8/multiprocessing/queues.py", line 88, in put
    self._start_thread()
  File "/home/sooh/.conda/envs/myenv/lib/python3.8/multiprocessing/queues.py", line 173, in _start_thread
    self._thread.start()
  File "/home/sooh/.conda/envs/myenv/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
KeyboardInterrupt: